//Responsive One Column Layout which changes to two-column layout at width = 900px and to one column layout at width below 600px.
export const data = {
  id: "3e48-e528-99ab98-0dba-aba8cda8",
  active: true,
  name: "Styleable container 1",
  label: "Styleable container 1",
  title: "",
  subtitle: "",
  order: "1",
  type: {
    group: "element",
    name: "Generic Block",
    id: "4cb9f85453db5110c733ddeeff7b12b4",
    route: "generic",
    props: [
      { element: "component_name", type: "string" },
      { element: "component_properties", type: "data_object" },
    ],
  },
  lazyLoad: "0",
  children: [
    {
      id: "98e1-d141-88aabb-4f2e-ba99b7b8",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "0",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "299d-c814-8abbb9-01db-b99855a9",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "e1ec563e53612110c733ddeeff7b120c",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "1bd7-92a9-98ab89-3381-baa86a9a",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "3da5",
          block_id: "3a9d-6289-a8aaab-3327-9ba8f8b8",
          parent_block_id: "a581-1f5d-89a889-6727-88a90b89",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: "",
      elementId: "styleable_container_3263450792314",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "a581-1f5d-89a889-6727-88a90b89",
      parent_block_id: "51a2-7a88-8a8b8b-bbee-89a9e5aa",
    },
    {
      id: "57bf-a762-b9aaa9-202e-98a9509a",
      active: true,
      name: "Styleable container 2",
      label: "Styleable container 2",
      title: "",
      subtitle: "",
      order: "1",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "05e7-8df6-988a8a-6ebc-a88a57aa",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "65ec563e53612110c733ddeeff7b120f",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "2273-86fc-9b8999-6077-a889859a",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "e48a",
          block_id: "6bc0-29e2-b88899-017d-888a559b",
          parent_block_id: "2ede-7322-b9b988-1e69-889924ab",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_2358d4b57",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "2ede-7322-b9b988-1e69-889924ab",
      parent_block_id: "51a2-7a88-8a8b8b-bbee-89a9e5aa",
    },
    {
      id: "1a17-7d9d-998b99-9c0f-989963ba",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "2",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "3aba-9984-9b8b88-5ecf-998959a8",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "e5ec563e53612110c733ddeeff7b1212",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "4339-f8c3-99a99a-467a-9ab82f8a",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "dfc6",
          block_id: "fc10-baca-b999ba-2d20-98a81fa8",
          parent_block_id: "a1ad-bd1d-88bb8b-fcf4-ab993e98",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_3604c6501",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "a1ad-bd1d-88bb8b-fcf4-ab993e98",
      parent_block_id: "51a2-7a88-8a8b8b-bbee-89a9e5aa",
    },
    {
      id: "5c29-6542-8babba-5439-8a9968b8",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "2",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "8c39-24f9-898888-2881-88aa8388",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "2c87-8efc-a9aaa8-338a-aba9c288",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "9208-25f5-8aa88b-1acf-bab9ae8b",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "b9e5",
          block_id: "9742-a5bc-ba9ba9-321d-8a893faa",
          parent_block_id: "ad69-0434-b9aaaa-8286-9aab00bb",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_3604ccb4008e5",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "ad69-0434-b9aaaa-8286-9aab00bb",
      parent_block_id: "51a2-7a88-8a8b8b-bbee-89a9e5aa",
    },
  ],
  props_details: {
    component_name: "sn-styleable-container",
    component_properties: {
      styles: {
        display: "grid",
        "grid-template-columns": "1fr",
        "grid-column-gap": "20px",
      },
      embedded_styles:
        "@media screen and (max-width: 600px) {  :host{  --gridtemplatecolumns: 1fr !important;  } }",
      embeddedStyles: "",
    },
  },
  props_details_display: {},
  props_overrides: {},
  pageParams: null,
  style: {},
  elementId: "styleable_container_155db0b0d",
  slotname: "",
  post_script: null,
  visibility: null,
  lazy_script: null,
  scope: "5df6db91ebe4011090fa99602a52289e",
  package: "5df6db91ebe4011090fa99602a52289e",
  slots: ["@default"],
  hasChildren: true,
  block_id: "51a2-7a88-8a8b8b-bbee-89a9e5aa",
};
