//Responsive Two Column Layout with changing to one column at width below 600px. 
export const data = {
  id: "3c1e-a653-ab99ba-50cd-bb88419b",
  active: true,
  name: "Styleable container 1",
  label: "Styleable container 1",
  title: "",
  subtitle: "",
  order: "1",
  type: {
    group: "element",
    name: "Generic Block",
    id: "4cb9f85453db5110c733ddeeff7b12b4",
    route: "generic",
    props: [
      { element: "component_name", type: "string" },
      { element: "component_properties", type: "data_object" },
    ],
  },
  lazyLoad: "0",
  children: [
    {
      id: "d3ae-2991-a898b9-469b-9b9a21b9",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "0",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "cb93-af8e-a8abbb-2d05-a899e4b9",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "e1ec563e53612110c733ddeeff7b120c",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "4422-acd1-aabb98-a022-a9994998",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "77cb",
          block_id: "dfdb-a51f-9bbab9-e0ad-b8ab1c9b",
          parent_block_id: "6d3f-8f1c-8aa9aa-faa5-89b99a99",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: "",
      elementId: "styleable_container_326345079b871",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "6d3f-8f1c-8aa9aa-faa5-89b99a99",
      parent_block_id: "3acf-d566-8aa9bb-9d26-9aab1cbb",
    },
    {
      id: "4dcd-1424-88a889-35cc-88982e99",
      active: true,
      name: "Styleable container 2",
      label: "Styleable container 2",
      title: "",
      subtitle: "",
      order: "1",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "186b-de4f-b88898-548b-a9a8fc8b",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "65ec563e53612110c733ddeeff7b120f",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "3d47-0f2a-bbaba8-f757-99abd888",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "cb33",
          block_id: "f2c7-168f-b89ba9-556e-99ab0489",
          parent_block_id: "85b3-34e3-9b89aa-8d4b-aaabd589",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_2358d371f",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "85b3-34e3-9b89aa-8d4b-aaabd589",
      parent_block_id: "3acf-d566-8aa9bb-9d26-9aab1cbb",
    },
    {
      id: "c8e0-e61b-8b8a88-c35d-aaa951ab",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "2",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "9f0e-8f02-9a8bab-67bd-88abddab",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "e5ec563e53612110c733ddeeff7b1212",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "ec48-e1e4-bbb889-a1af-a89835aa",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "0957",
          block_id: "6ebf-be55-89aaba-a449-9889158a",
          parent_block_id: "e33d-7b5a-9bbb9b-66a7-8aaad39b",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_3604c42b9",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "e33d-7b5a-9bbb9b-66a7-8aaad39b",
      parent_block_id: "3acf-d566-8aa9bb-9d26-9aab1cbb",
    },
  ],
  props_details: {
    component_name: "sn-styleable-container",
    component_properties:
      '{"styles":{"display":"grid","grid-template-columns":"var(--gridtemplatecolumns, \\"1fr 1fr\\")","grid-column-gap":"20px"},"embedded_styles":"@media screen and (max-width: 600px) {  :host{  --gridtemplatecolumns: 1fr !important;  } }"}',
  },
  props_details_display: {},
  props_overrides: {},
  pageParams: null,
  style: { "--gridtemplatecolumns": "1fr 1fr" },
  elementId: "styleable_container_155db7090",
  slotname: "",
  post_script: null,
  visibility: null,
  lazy_script: null,
  scope: "5df6db91ebe4011090fa99602a52289e",
  package: "5df6db91ebe4011090fa99602a52289e",
  slots: ["@default"],
  block_id: "3acf-d566-8aa9bb-9d26-9aab1cbb",
};
