//Responsive 4 Column Layout which changes to two-column layout at width = 900px and to one column layout at width below 600px.
export const data = {
  id: "3440-bb1c-aa899b-cc68-8a8bd38a",
  active: true,
  name: "Styleable container 1",
  label: "Styleable container 1",
  title: "",
  subtitle: "",
  order: "1",
  type: {
    group: "element",
    name: "Generic Block",
    id: "4cb9f85453db5110c733ddeeff7b12b4",
    route: "generic",
    props: [
      { element: "component_name", type: "string" },
      { element: "component_properties", type: "data_object" },
    ],
  },
  lazyLoad: "0",
  children: [
    {
      id: "41ae-6d50-bbabba-44d6-8aaa738a",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "0",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "54a0-8689-89ba88-58f4-89ba25aa",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "e1ec563e53612110c733ddeeff7b120c",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "07d9",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "2326-3805-9a9b88-a7ba-b9884c8a",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "b99f",
          block_id: "19cf-44b9-b9989a-df6e-9bb85699",
          parent_block_id: "b598-ac5f-89b989-c64b-a88a90a8",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: "",
      elementId: "styleable_container_326345079cef4",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "b598-ac5f-89b989-c64b-a88a90a8",
      parent_block_id: "ca7b-08ca-99ab9b-c72f-998953a8",
    },
    {
      id: "17bb-d750-8bb8aa-9afa-aa98508a",
      active: true,
      name: "Styleable container 2",
      label: "Styleable container 2",
      title: "",
      subtitle: "",
      order: "1",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "bc56-df3d-89b8ab-0e51-8a8a209b",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "65ec563e53612110c733ddeeff7b120f",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "07d9",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "d632-c477-8ab99a-4bba-a98bba8b",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "77c1",
          block_id: "1113-2d16-b889a8-8728-8988dd89",
          parent_block_id: "a558-6cca-abb9bb-aec5-9aa8d5a9",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_2358d3da8",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "a558-6cca-abb9bb-aec5-9aa8d5a9",
      parent_block_id: "ca7b-08ca-99ab9b-c72f-998953a8",
    },
    {
      id: "88d8-685b-8a898a-bc44-bbbacbaa",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "2",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "6f17-a7c0-aaabaa-e5a8-8aa8c988",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "e5ec563e53612110c733ddeeff7b1212",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "07d9",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "f955-3a68-bb9889-1c3c-b89835bb",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "89be",
          block_id: "5a52-d376-aa8998-ab52-8aaa88ba",
          parent_block_id: "905c-b595-98999a-0ce6-9998f38b",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_3604c9315",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "905c-b595-98999a-0ce6-9998f38b",
      parent_block_id: "ca7b-08ca-99ab9b-c72f-998953a8",
    },
    {
      id: "0a89-1cb7-9abb98-54d5-98b9d0b9",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "2",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "2184-03de-bab9b9-7c0f-889ad19b",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "2c87-8efc-a9aaa8-338a-aba9c288",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_3604ccb40",
                  "07d9",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "d176-9a41-98bb99-48dd-ab993b89",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "5cef",
          block_id: "8518-4ea9-a98889-a6a1-8b898c9b",
          parent_block_id: "518c-de66-babb89-481c-b99ae099",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_3604ccb40d325",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "518c-de66-babb89-481c-b99ae099",
      parent_block_id: "ca7b-08ca-99ab9b-c72f-998953a8",
    },
  ],
  props_details: {
    component_name: "sn-styleable-container",
    component_properties: {
      styles: {
        display: "grid",
        "grid-template-columns":
          'var(--gridtemplatecolumns, "1fr 1fr 1fr 1fr")',
        "grid-column-gap": "20px",
      },
      embedded_styles:
        "@media screen and (max-width: 600px) {  :host{  --gridtemplatecolumns: 1fr !important;  } }",
      embeddedStyles:
        "@media only screen and (min-width: 901px) and (max-width: 1200px) { :host { --gridtemplatecolumns: 1fr 1fr 1fr !important; }} @media only screen and (min-width: 601px) and (max-width: 900px) { :host { --gridtemplatecolumns: 1fr 1fr !important; }} @media only screen and (max-width: 600px) { :host { --gridtemplatecolumns: 1fr !important; }}",
    },
  },
  props_details_display: {},
  props_overrides: {},
  pageParams: null,
  style: { "--gridtemplatecolumns": "1fr 1fr 1fr 1fr" },
  elementId: "styleable_container_155dbc1a1",
  slotname: "",
  post_script: null,
  visibility: null,
  lazy_script: null,
  scope: "5df6db91ebe4011090fa99602a52289e",
  package: "5df6db91ebe4011090fa99602a52289e",
  slots: ["@default"],
  hasChildren: true,
  block_id: "ca7b-08ca-99ab9b-c72f-998953a8",
};
