//Responsive Three Column Layout which changes to two-column layout at width = 900px and to one column layout at width below 600px.
export const data = {
  id: "80fa-ec79-9bb8b8-6ae3-bb99bbbb",
  active: true,
  name: "Styleable container 1",
  label: "Styleable container 1",
  title: "",
  subtitle: "",
  order: "1",
  type: {
    group: "element",
    name: "Generic Block",
    id: "4cb9f85453db5110c733ddeeff7b12b4",
    route: "generic",
    props: [
      { element: "component_name", type: "string" },
      { element: "component_properties", type: "data_object" },
    ],
  },
  lazyLoad: "0",
  children: [
    {
      id: "58c4-ba81-89ab88-50a0-9aabc0aa",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "0",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "8b30-43fe-aaba98-b4e1-89bb39aa",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "98fd-db44-9a99a9-5d5c-89a85788",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "d130-6fb0-a9abab-a407-a99b5aba",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "efdd",
          block_id: "5482-0e89-a8baa8-48f5-9abb5aa8",
          parent_block_id: "5c2a-7efe-98898b-6762-bbab1388",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: "",
      elementId: "styleable_container_326345079b8711ab28957",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "5c2a-7efe-98898b-6762-bbab1388",
      parent_block_id: "d888-6f76-bb88b9-9a23-b89ae688",
    },
    {
      id: "ff82-b4de-9bbb88-6056-9b9932bb",
      active: true,
      name: "Styleable container 2",
      label: "Styleable container 2",
      title: "",
      subtitle: "",
      order: "1",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "5e3a-e88f-989ba8-25f5-bab9ce98",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "524b-ddd6-aaa9ab-f9ca-a9a82798",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "9f6a-f131-a9bb8b-28c3-aaabfab9",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "637d",
          block_id: "f1cb-a444-bbb8aa-8da8-bbb98ab8",
          parent_block_id: "4d58-bfcb-ab8bb8-c811-98990cab",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_2358d371f294ee42c",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "4d58-bfcb-ab8bb8-c811-98990cab",
      parent_block_id: "d888-6f76-bb88b9-9a23-b89ae688",
    },
    {
      id: "2d3f-55c6-a8bbab-4677-8a99088a",
      active: true,
      name: "Styleable container 3",
      label: "Styleable container 3",
      title: "",
      subtitle: "",
      order: "2",
      type: {
        group: "element",
        name: "Generic Block",
        id: "4cb9f85453db5110c733ddeeff7b12b4",
        route: "generic",
        props: [
          { element: "component_name", type: "string" },
          { element: "component_properties", type: "data_object" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "4f6d-39c1-bba899-4f76-a9abbcab",
          active: true,
          name: "[Placeholder]",
          slotname: "@default",
          props_details: {
            component_name: "sn-ace-placeholder-content",
            component_properties: {
              parentblockid: "a1fb-911e-b9b8aa-d58f-b88981aa",
              popoverblock: {},
              type: "BLOCK_TYPE",
              popoverComponent: "sn-ace-base-builder-popover",
              blockcontext: {},
              resources: {
                elementIdCollection: [
                  "accordion_1",
                  "accordion_item_1",
                  "heading_1",
                  "accordion_item_2",
                  "simple_card_with_button_1",
                  "35a9",
                  "958e",
                  "823e",
                  "0c49",
                  "4bab",
                  "1975",
                  "7f14",
                  "5261",
                  "button_13d5c",
                  "b183",
                  "37a9",
                  "b844",
                  "3442",
                  "28a4",
                  "e19d",
                  "6c6e",
                  "9e4c",
                  "05d5",
                  "7eed",
                  "9def",
                  "76ac",
                  "4f16",
                  "4b88",
                  "cd8c",
                  "e5ae",
                  "269c",
                  "fdeb",
                  "00d4",
                  "e6ef",
                  "e448",
                  "0a42",
                  "91b6",
                  "8496",
                  "e074",
                  "2df2",
                  "c9c3",
                  "93c3",
                  "dd30",
                  "cd0f",
                  "2486",
                  "1416",
                  "f8c1",
                  "c79a",
                  "387e",
                  "416f",
                  "dynamic_container_32a32",
                  "heading_2fc90",
                  "rich_text_1b809",
                  "repeater_1d664",
                  "enhance_the_journey_card_16339",
                  "styleable_container_155db",
                  "styleable_container_326345079",
                  "styleable_container_2358d",
                  "styleable_container_3604c",
                  "styleable_container_155db70904d42",
                  "styleable_container_326345079b871d375",
                  "styleable_container_155db7090528c",
                  "styleable_container_326345079b8711ab2",
                  "styleable_container_2358d371f294e",
                  "styleable_container_3604c42b9e382",
                  "simple_card_with_button_2",
                  "styleable_container_2358d371f0987",
                  "simple_card_with_button_3",
                  "styleable_container_3604c42b97b48",
                  "simple_card_with_button_4",
                ],
              },
              slotname: "@default",
              placeholderBlockId: "873d-538c-bab9a9-4a39-aaa9568a",
            },
          },
          type: { route: "generic" },
          children: [],
          slots: [],
          elementId: "edf4",
          block_id: "19f2-e36b-ba99bb-984e-89bbf599",
          parent_block_id: "f109-03f0-b9bb9b-d774-88aac69a",
        },
      ],
      props_details: {
        component_name: "sn-styleable-container",
        component_properties: '{"styles":{}}',
      },
      props_details_display: {},
      props_overrides: {},
      style: {},
      elementId: "styleable_container_3604c42b9e3829440",
      slotname: "@default",
      post_script:
        "(function(context, pageParams){  /*   context = {    'block_id': @sysId,    'name': @String,    'title': @String,    'subtitle': @String,    'order': @Number,    'type': @Object,    'children': @Array[context],    'props_details': @Object   };  */ })(context, pageParams);",
      visibility: "answer=true;",
      lazy_script: null,
      scope: "5df6db91ebe4011090fa99602a52289e",
      package: "5df6db91ebe4011090fa99602a52289e",
      slots: ["@default"],
      block_id: "f109-03f0-b9bb9b-d774-88aac69a",
      parent_block_id: "d888-6f76-bb88b9-9a23-b89ae688",
    },
  ],
  props_details: {
    component_name: "sn-styleable-container",
    component_properties: {
      styles: {
        display: "grid",
        "grid-template-columns": 'var(--gridtemplatecolumns, "1fr 1fr 1fr")',
        "grid-column-gap": "20px",
      },
      embedded_styles:
        "@media screen and (max-width: 600px) {  :host{  --gridtemplatecolumns: 1fr !important;  } }",
      embeddedStyles:
        "@media only screen and (min-width: 601px) and (max-width: 900px) { :host { --gridtemplatecolumns: 1fr 1fr !important; }} @media only screen and (max-width: 600px) { :host { --gridtemplatecolumns: 1fr !important; }}",
    },
  },
  props_details_display: {},
  props_overrides: {},
  pageParams: null,
  style: { "--gridtemplatecolumns": "1fr 1fr 1fr" },
  elementId: "styleable_container_155db7090528c9176",
  slotname: "@default",
  post_script: null,
  visibility: null,
  lazy_script: null,
  scope: "5df6db91ebe4011090fa99602a52289e",
  package: "5df6db91ebe4011090fa99602a52289e",
  slots: ["@default"],
  hasChildren: true,
  block_id: "d888-6f76-bb88b9-9a23-b89ae688",
};
