//CTA Card
export const data = {
  id: "b457-5ba4-8a8aab-abc6-99bbb58b",
  active: true,
  name: "Integrate VA with portal Card",
  label: "Integrate VA with portal Card",
  title: "",
  subtitle: "",
  order: "30",
  type: {
    group: "element",
    name: "Carousel Card",
    id: "34421ba87702011039ac088b3a1061a9",
    route: "carousel-card",
    props: [],
    macroponent: "bf1e8fa47702011039ac088b3a106145",
  },
  lazyLoad: "0",
  children: [
    {
      id: "2632-d9d5-9a989a-22d9-8ba9b3bb",
      active: true,
      name: "Portals Card Screen 1",
      label: "Portals Card Screen 1",
      title: "Launch",
      subtitle: "Add your bot to a portal",
      order: "10",
      type: {
        group: "element",
        name: "Carousel Element",
        id: "4b921fa87702011039ac088b3a1061e0",
        route: "carousel-element",
        props: [
          { element: "last_reviewed_on", type: "glide_date" },
          { element: "description", type: "translated_text" },
          { element: "image", type: "url" },
          { element: "type", type: "choice" },
        ],
      },
      lazyLoad: "0",
      children: [],
      props_details: {
        last_reviewed_on: "",
        description:
          "Add your bot to an employee or customer portal so your users can begin to get the chat support they need.",
        image: "/images/ci_landingexp_portals.png",
        type: "Content",
      },
      props_details_display: {},
      props_overrides: {},
      pageParams: "",
      style: {},
      elementId: "d56a",
      slotname: "",
      post_script:
        '(function(context) {\n    var gr = new GlideRecord(\'sp_agent_chat_config\');\n    gr.addActiveQuery();\n    gr.query();\n    var portalConfigs = [];\n    while (gr.next()) {\n        var portalConfigId = gr.getDisplayValue("sys_id");\n        portalConfigs.push({\n            id: portalConfigId,\n            label: gr.getDisplayValue("name"),\n            event_name: \'VA_PORTAL_RECORD_LINK_CLICK\',\n            link: "/sp_agent_chat_config.do?sys_id=" + portalConfigId,\n            external: true\n        });\n    }\n    context.splitButtonActionData = {\n        "label": gs.getMessage("Add to portal"),\n        "link": "/sp_agent_chat_config.do?sys_id=-1",\n        "external": true,\n        "items": portalConfigs\n    };\n\tcontext.props_details.image = \'/images/ci_landingexp_portals.png\';\n\treturn context;\n})(context);',
      visibility: "",
      lazy_script: "",
      scope: "53b1b0e79761011018b2fa98c253afcc",
      package: "53b1b0e79761011018b2fa98c253afcc",
      splitButtonActionData: {
        label: "Add to portal",
        link: "/sp_agent_chat_config.do?sys_id=-1",
        external: true,
        items: [
          {
            id: "2f3c06b41b5570108d16ca64604bcbd0",
            label: "EC Polaris ",
            event_name: "VA_PORTAL_RECORD_LINK_CLICK",
            link: "/sp_agent_chat_config.do?sys_id=2f3c06b41b5570108d16ca64604bcbd0",
            external: true,
          },
          {
            id: "305eb5d8534000102905ddeeff7b1211",
            label: "ESC Chat",
            event_name: "VA_PORTAL_RECORD_LINK_CLICK",
            link: "/sp_agent_chat_config.do?sys_id=305eb5d8534000102905ddeeff7b1211",
            external: true,
          },
          {
            id: "46f9a60277943300454792718a10619d",
            label: "Service Portal Agent Chat Config",
            event_name: "VA_PORTAL_RECORD_LINK_CLICK",
            link: "/sp_agent_chat_config.do?sys_id=46f9a60277943300454792718a10619d",
            external: true,
          },
        ],
      },
      slots: [],
      block_id: "3488-f4f0-8aba9a-fb15-ba8b88b9",
      parent_block_id: "f26d-10a9-bbb89b-4638-aa893b88",
    },
    {
      id: "b677-d225-8bb99b-6a0a-9a888798",
      active: true,
      name: "Portals Card Screen 2",
      label: "Portals Card Screen 2",
      title: "Test",
      subtitle: "Interact with your bot",
      order: "20",
      type: {
        group: "element",
        name: "Carousel Element",
        id: "4b921fa87702011039ac088b3a1061e0",
        route: "carousel-element",
        props: [
          { element: "last_reviewed_on", type: "glide_date" },
          { element: "description", type: "translated_text" },
          { element: "image", type: "url" },
          { element: "type", type: "choice" },
        ],
      },
      lazyLoad: "0",
      children: [],
      props_details: {
        last_reviewed_on: "",
        description:
          "One of the best ways to evaluate your chat support experience is to try it out for yourself. Open an employee or customer portal and give it a test.",
        image: "/images/ci_landingexp_portals.png",
        type: "Content",
      },
      props_details_display: {},
      props_overrides: {},
      pageParams: "",
      style: {},
      elementId: "c6d3",
      slotname: "",
      post_script:
        '(function(context) {\n\n    var gr = new GlideRecord(\'sp_agent_chat_config\');\n    gr.addActiveQuery();\n    gr.query();\n    var portalIds = [];\n    var portals = [];\n    while (gr.next()) {\n        if (gr.getValue(\'portal\')) {\n            gr.getValue(\'portal\').split(",").forEach(function(portalId) {\n                if (portalIds.indexOf(portalId) == -1) {\n                    portalIds.push(portalId);\n                    var portalGR = new GlideRecord(\'sp_portal\');\n                    portalGR.get(portalId);\n                    var urlSuffix = portalGR.getDisplayValue("url_suffix");\n                    portals.push({\n                        "id": urlSuffix,\n                        "label": portalGR.getDisplayValue("title"),\n                        "link": "/" + urlSuffix\n                    });\n                }\n            });\n        }\n    }\n    context.splitButtonActionData = {\n        "label": gs.getMessage("Open portal"),\n        "link": "",\n        "items": portals\n    };\n\tcontext.props_details.image = \'/images/ci_landingexp_portals.png\';\n\treturn context;\n})(context);',
      visibility: "",
      lazy_script: "",
      scope: "53b1b0e79761011018b2fa98c253afcc",
      package: "53b1b0e79761011018b2fa98c253afcc",
      splitButtonActionData: {
        label: "Open portal",
        link: "",
        items: [
          { id: "esc", label: "Employee Center", link: "/esc" },
          { id: "sp", label: "Service Portal ", link: "/sp" },
        ],
      },
      slots: [],
      block_id: "1eee-b225-98a989-2b62-99bbdda8",
      parent_block_id: "f26d-10a9-bbb89b-4638-aa893b88",
    },
  ],
  props_details: {
    dismissed_on: "",
    last_action_on: "",
    last_reviewed_on: "",
    showDismiss: true,
  },
  props_details_display: {},
  props_overrides: {},
  pageParams: "",
  style: { width: "20rem" },
  elementId: "194f",
  slotname: "@default",
  post_script:
    "(function(context) {\n\tvar ciUtil = new sn_oe_sfs.CIUtil();\n\tciUtil.setCtaCardPropsFromContext(context);\n\t\n    if (isNoPortalActive(context)) {\n        context.__is_complete = false;\n    } else {\n        if (isCardNeverReviewed(context)) {\n            context.__is_complete = false;\n        }\n    }\n\n    function isCardNeverReviewed(context) {\n        return !context.props_details.last_reviewed_on;\n    }\n\n    function isNoPortalActive(context) {\n        var gr = new GlideRecord('sp_agent_chat_config');\n        gr.addActiveQuery();\n        gr.setLimit(1);\n        gr.query();\n        return !gr.hasNext();\n    }\n})(context);",
  visibility: "",
  lazy_script: "",
  scope: "53b1b0e79761011018b2fa98c253afcc",
  package: "53b1b0e79761011018b2fa98c253afcc",
  __is_complete: false,
  blockcontext: { provider_name: "" },
  slots: [],
  hasChildren: true,
  block_id: "f26d-10a9-bbb89b-4638-aa893b88",
};
