//Two Cards Container
export const data = {
  id: "84e7-2220-aa988b-85e7-888bb2bb",
  active: true,
  name: "Topic Recommendations Two Card Container",
  label: "Topic Recommendations Two Card Container",
  title: "Topic Recommendations",
  subtitle: "",
  order: "10",
  type: {
    group: "element",
    name: "CI Admin Experience - Two Simple Cards With Buttons",
    id: "28b8f1b9c3310110fc869bc8a840dddf",
    route: "two_simple_cards_with_buttons",
    props: [{ element: "highlight", type: "boolean" }],
    macroponent: "609a6fe0c3420110fc869bc8a840dd41",
  },
  lazyLoad: "0",
  children: [
    {
      id: "3df8-de9a-9a8a9a-6729-9b8958a8",
      active: true,
      name: "Topic Recommendations Card One",
      label: "Topic Recommendations Card One",
      title: "Configure Topic Recommendations",
      subtitle:
        "Review the default criteria for analyzing the data sources that will be used in Topic Recommendations.",
      order: "10",
      type: {
        group: "element",
        name: "CI Admin Experience - Two Card Element",
        id: "02242f43c3710110fc869bc8a840dd5b",
        route: "ci-admin-experience--two-card-element",
        props: [
          { element: "footer_type", type: "choice" },
          { element: "footer", type: "translated_text" },
          { element: "status", type: "choice" },
        ],
        macroponent: "287da3a4c3420110fc869bc8a840ddc4",
      },
      lazyLoad: "0",
      children: [
        {
          id: "ac4b-2830-a8aaa8-9a4f-abab39a8",
          active: true,
          name: "Topic Recommendations View All Button",
          label: "Topic Recommendations View All Button",
          title: "View All",
          subtitle: "",
          order: "",
          type: {
            group: "action",
            name: "Button",
            id: "02c8c279c3e401104b8e88c7c840dde2",
            route: "button",
            props: [
              { element: "action_type", type: "string" },
              { element: "link", type: "url" },
              { element: "event_name", type: "string" },
              { element: "variant", type: "string" },
              { element: "button_size", type: "string" },
              { element: "icon", type: "string" },
              { element: "disabled", type: "boolean" },
              { element: "aria_properties", type: "json" },
            ],
            macroponent: "87b330a2536141102958ddeeff7b12b2",
          },
          lazyLoad: "0",
          children: [],
          props_details: {
            action_type: "event",
            link: "",
            event_name: "TOPIC_RECOMMENDATIONS_VIEW_ALL",
            variant: "secondary",
            button_size: "sm",
            icon: "",
            disabled: "false",
            aria_properties: "",
          },
          props_details_display: {},
          props_overrides: {},
          pageParams: { bare: true, scrollable: "both", headerLevel: "1" },
          style: {},
          elementId: "86d9",
          slotname: "",
          post_script: "",
          visibility: "answer = new CIPlugin.TopicRecommender().isActive();",
          lazy_script: "",
          scope: "53b1b0e79761011018b2fa98c253afcc",
          package: "53b1b0e79761011018b2fa98c253afcc",
          slots: [],
          block_id: "fca8-b620-9bb9ab-3d7a-bbab7a89",
          parent_block_id: "2917-37c3-bb88a8-5066-bb9abbaa",
        },
      ],
      props_details: {
        footer_type: "text",
        footer: "",
        status: "",
        footer_text: "Default criteria (0)",
      },
      props_details_display: {},
      props_overrides: {},
      pageParams: { bare: true, scrollable: "both", headerLevel: "1" },
      style: {},
      elementId: "dd89",
      slotname: "",
      post_script:
        "(function(context){\n\tif(CIPlugin.TopicRecommender().isActive()) {\n\t\tvar trSettingsCount = new sn_oe_sfs.CIUtil().getTopicRecommendationSettingsCount();\n\t\tcontext.props_details.footer_text = gs.getMessage(\"Default criteria ({0})\", trSettingsCount);\n\t} else {\n\t\tcontext.props_details.footer_text = '';\n\t}\n})(context);",
      visibility: "",
      lazy_script: "",
      scope: "53b1b0e79761011018b2fa98c253afcc",
      package: "53b1b0e79761011018b2fa98c253afcc",
      slots: [],
      block_id: "2917-37c3-bb88a8-5066-bb9abbaa",
      parent_block_id: "0d2c-bcd6-ba999b-480e-a89ab6aa",
    },
    {
      id: "4b06-348e-aa89a8-59d6-a8a87589",
      active: true,
      name: "Topic Recommendations Card Two",
      label: "Topic Recommendations Card Two",
      title: "See topics recommended just for you",
      subtitle:
        "Here's what we suggest you can automate with VA based on what your users are most often contacting you about.",
      order: "20",
      type: {
        group: "element",
        name: "CI Admin Experience - Two Card Element",
        id: "02242f43c3710110fc869bc8a840dd5b",
        route: "ci-admin-experience--two-card-element",
        props: [
          { element: "footer_type", type: "choice" },
          { element: "footer", type: "translated_text" },
          { element: "status", type: "choice" },
        ],
        macroponent: "287da3a4c3420110fc869bc8a840ddc4",
      },
      lazyLoad: "0",
      children: [
        {
          id: "fa9e-a061-9aaa88-565b-8bb9deba",
          active: true,
          name: "Topic Recommendations Plugin Button",
          label: "Topic Recommendations Plugin Button",
          title: "Go to Topic Recommendations",
          subtitle: "",
          order: "",
          type: {
            group: "action",
            name: "Button",
            id: "02c8c279c3e401104b8e88c7c840dde2",
            route: "button",
            props: [
              { element: "action_type", type: "string" },
              { element: "link", type: "url" },
              { element: "event_name", type: "string" },
              { element: "variant", type: "string" },
              { element: "button_size", type: "string" },
              { element: "icon", type: "string" },
              { element: "disabled", type: "boolean" },
              { element: "aria_properties", type: "json" },
            ],
            macroponent: "87b330a2536141102958ddeeff7b12b2",
          },
          lazyLoad: "0",
          children: [],
          props_details: {
            action_type: "link",
            link: "/nav_to.do?uri=%2F$topic-recommender.do%23%2Freports",
            event_name: "",
            variant: "secondary",
            button_size: "sm",
            icon: "open-link-right-fill",
            disabled: "false",
            aria_properties: "",
          },
          props_details_display: {},
          props_overrides: {},
          pageParams: { bare: true, scrollable: "both", headerLevel: "1" },
          style: {},
          elementId: "c5dc",
          slotname: "",
          post_script:
            "(function(context){\n\tcontext.props_details.link = '/nav_to.do?uri=%2F$topic-recommender.do%23%2Freports';\n})(context);",
          visibility: "answer = CIPlugin.TopicRecommender().isActive();",
          lazy_script: "",
          scope: "53b1b0e79761011018b2fa98c253afcc",
          package: "53b1b0e79761011018b2fa98c253afcc",
          slots: [],
          block_id: "ed07-c2b4-8aa9ab-d3d4-bbab9599",
          parent_block_id: "e940-f03c-a89baa-801d-b9b82489",
        },
      ],
      props_details: { footer_type: "text", footer: "", status: "" },
      props_details_display: {},
      props_overrides: {},
      pageParams: { bare: true, scrollable: "both", headerLevel: "1" },
      style: {},
      elementId: "fcc7",
      slotname: "",
      post_script:
        "(function(context){\n\tif(!CIPlugin.TopicRecommender().isActive()) {\n\t\tcontext.title = '';\n\t\tcontext.subtitle = '';\n\t\tcontext.props_details.footer_text = '';\n\t}\n})(context);",
      visibility: "",
      lazy_script: "",
      scope: "53b1b0e79761011018b2fa98c253afcc",
      package: "53b1b0e79761011018b2fa98c253afcc",
      slots: [],
      block_id: "e940-f03c-a89baa-801d-b9b82489",
      parent_block_id: "0d2c-bcd6-ba999b-480e-a89ab6aa",
    },
  ],
  props_details: { highlight: false },
  props_details_display: {},
  props_overrides: {},
  pageParams: { bare: true, scrollable: "both", headerLevel: "1" },
  style: { width: "50rem" },
  elementId: "b4bb",
  slotname: "@default",
  post_script:
    "(function(context){\n\tif(!CIPlugin.TopicRecommender().isActive()) {\n\t\tcontext.props_details.highlight = true;\n\t} else {\n\t\tcontext.props_details.highlight = false;\n\t}\n})(context);",
  visibility: "",
  lazy_script: "",
  scope: "53b1b0e79761011018b2fa98c253afcc",
  package: "53b1b0e79761011018b2fa98c253afcc",
  blockcontext: { provider_name: "" },
  slots: [],
  hasChildren: true,
  block_id: "0d2c-bcd6-ba999b-480e-a89ab6aa",
};
