//CTA Card
export const data = {
  id: "239a-cf31-8aba9b-855e-a98813a9",
  active: true,
  name: "Profanity Filter Card",
  label: "Profanity Filter Card",
  title: "",
  subtitle: "",
  order: "130",
  type: {
    group: "element",
    name: "Carousel Card",
    id: "34421ba87702011039ac088b3a1061a9",
    route: "carousel-card",
    props: [],
    macroponent: "bf1e8fa47702011039ac088b3a106145",
  },
  lazyLoad: "0",
  children: [
    {
      id: "a1ea-04b9-988898-ee56-8a8a9bbb",
      active: true,
      name: "Profanity Filter Card Screen 1",
      label: "Profanity Filter Card Screen 1",
      title: "Protect",
      subtitle: "Get Profanity Filter",
      order: "10",
      type: {
        group: "element",
        name: "Carousel Element",
        id: "4b921fa87702011039ac088b3a1061e0",
        route: "carousel-element",
        props: [
          { element: "last_reviewed_on", type: "glide_date" },
          { element: "description", type: "translated_text" },
          { element: "image", type: "url" },
          { element: "type", type: "choice" },
        ],
      },
      lazyLoad: "0",
      children: [
        {
          id: "b874-a6bb-8898ab-7c78-abbb34a8",
          active: true,
          name: "CI Profanity Filter plugin Action",
          label: "CI Profanity Filter plugin Action",
          title: "Profanity Filter plugin",
          subtitle: "",
          order: "10",
          type: {
            group: "custom",
            name: "CI Admin Experience - Plugin Card",
            id: "04d5765a530011102958ddeeff7b12ec",
            route: "ci-plugin-card",
            props: [
              { element: "button_label", type: "translated_text" },
              { element: "image", type: "url" },
              { element: "link", type: "url" },
              { element: "icon", type: "string" },
            ],
            macroponent: "d796b29a530011102958ddeeff7b128a",
          },
          lazyLoad: "0",
          children: [],
          props_details: {
            button_label: "Get Profanity Filter Plugin",
            image: "",
            link: "https://store.servicenow.com/sn_appstore_store.do#!/store/application/77d07c3b7352201076d81f8afaf6a7bb",
            icon: "open-link-right-fill",
            size: "sm",
          },
          props_details_display: {},
          props_overrides: {},
          pageParams: "",
          style: {},
          elementId: "26bf",
          slotname: "",
          post_script:
            "(function(context) {\n    context.props_details.link = CIPlugin.ProfanityApp().getAppLink();\n\tcontext.props_details.size = 'sm';\n\n})(context);",
          visibility:
            "answer = !GlidePluginManager.isActive('com.sn.va.profanity');\n",
          lazy_script: "",
          scope: "53b1b0e79761011018b2fa98c253afcc",
          package: "53b1b0e79761011018b2fa98c253afcc",
          slots: [],
          block_id: "bbe1-5456-8a8899-11d5-a9894f99",
          parent_block_id: "f17f-ba20-9a8ab8-20ff-9abb9c9a",
        },
      ],
      props_details: {
        last_reviewed_on: "",
        description:
          "Keep conversations professional by preventing both users and agents from using prohibited words and phrases.",
        image: "/images/ci_landingexp_profanityfilter.png",
        type: "Content",
      },
      props_details_display: {},
      props_overrides: {},
      pageParams: "",
      style: {},
      elementId: "5344",
      slotname: "",
      post_script:
        "(function(context){ \n\t\n\tcontext.props_details.image = '/images/ci_landingexp_profanityfilter.png';\n\tif(GlidePluginManager.isActive('com.sn.va.profanity')) {\n\t\t//State: Profanity Filter has been installed\n\t\tcontext.subtitle = gs.getMessage('Tune the Profanity Filter');\n\t\tcontext.props_details.description = gs.getMessage('Continue to keep conversations professional by preventing both users and agents from using prohibited words and phrases.');\n\t}\n\telse {\n\t\t//State: Install Profanity Filter\n\t\tcontext.subtitle = gs.getMessage('Get Profanity Filter');\n\t\tcontext.props_details.description = gs.getMessage('Keep conversations professional by preventing both users and agents from using prohibited words and phrases.');\n\t\tcontext.__is_complete = false;\n\t}\n\t\n\t\n})(context);",
      visibility: "",
      lazy_script: "",
      scope: "53b1b0e79761011018b2fa98c253afcc",
      package: "53b1b0e79761011018b2fa98c253afcc",
      __is_complete: false,
      slots: [],
      block_id: "f17f-ba20-9a8ab8-20ff-9abb9c9a",
      parent_block_id: "d371-d0e2-a9ba8b-4b22-98a8398a",
    },
  ],
  props_details: {
    dismissed_on: "",
    last_action_on: "",
    last_reviewed_on: "",
    showDismiss: true,
  },
  props_details_display: {},
  props_overrides: {},
  pageParams: "",
  style: { width: "20rem" },
  elementId: "e49c",
  slotname: "@default",
  post_script:
    "(function(context) {\n\tvar ciUtil = new sn_oe_sfs.CIUtil();\n\tciUtil.setCtaCardPropsFromContext(context);\n})(context);",
  visibility: "",
  lazy_script: "",
  scope: "53b1b0e79761011018b2fa98c253afcc",
  package: "53b1b0e79761011018b2fa98c253afcc",
  blockcontext: { provider_name: "" },
  slots: [],
  hasChildren: true,
  block_id: "d371-d0e2-a9ba8b-4b22-98a8398a",
};
